src/Entity/Main/Users.php
<?php

namespace App\Entity\Main;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use App\Repository\Main\UsersRepository;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 */
class Users implements UserInterface
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $votes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $confirmkey;

    /**
     * @ORM\OneToMany(targetEntity=FTopic::class, mappedBy="owner")
     */
    private $topics;

    /**
     * @ORM\OneToMany(targetEntity=FMessage::class, mappedBy="owner")
     */
    private $messages;

    /**
     * @ORM\OneToMany(targetEntity=Ticket::class, mappedBy="owner")
     */
    private $tickets;

    /**
     * @ORM\OneToMany(targetEntity=TMessage::class, mappedBy="owner")
     */
    private $tickets_messages;

    /**
     * @ORM\OneToMany(targetEntity=news::class, mappedBy="owner")
     */
    private $news;

    /**
     * @ORM\OneToMany(targetEntity=NComments::class, mappedBy="owner")
     */
    private $newsComments;

    /**
     * @ORM\OneToMany(targetEntity=Notification::class, mappedBy="owner")
     */
    private $notifications;


    public function __construct()
    {
        $this->topics = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->tickets = new ArrayCollection();
        $this->tickets_messages = new ArrayCollection();
        $this->news = new ArrayCollection();
        $this->newsComments = new ArrayCollection();
        $this->notifications = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getVotes(): ?int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    public function getConfirmkey(): ?string
    {
        return $this->confirmkey;
    }

    public function setConfirmkey(string $confirmkey): self
    {
        $this->confirmkey = $confirmkey;

        return $this;
    }

    public function getRoles()
    {
        return ['ROLE_USER'];
    }

    public function getSalt() {}

    public function getUsername()
    {
        return $this->pseudo;
    }

    public function eraseCredentials() {}

    /**
     * @return Collection|FTopic[]
     */
    public function getTopics(): Collection
    {
        return $this->topics;
    }

    public function addTopic(FTopic $topic): self
    {
        if (!$this->topics->contains($topic)) {
            $this->topics[] = $topic;
            $topic->setOwner($this);
        }

        return $this;
    }

    public function removeTopic(FTopic $topic): self
    {
        if ($this->topics->contains($topic)) {
            $this->topics->removeElement($topic);
            // set the owning side to null (unless already changed)
            if ($topic->getOwner() === $this) {
                $topic->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|FMessage[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(FMessage $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setOwner($this);
        }

        return $this;
    }

    public function removeMessage(FMessage $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getOwner() === $this) {
                $message->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Ticket[]
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    public function addTicket(Ticket $ticket): self
    {
        if (!$this->tickets->contains($ticket)) {
            $this->tickets[] = $ticket;
            $ticket->setOwner($this);
        }

        return $this;
    }

    public function removeTicket(Ticket $ticket): self
    {
        if ($this->tickets->contains($ticket)) {
            $this->tickets->removeElement($ticket);
            // set the owning side to null (unless already changed)
            if ($ticket->getOwner() === $this) {
                $ticket->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|TMessage[]
     */
    public function getTicketsMessages(): Collection
    {
        return $this->tickets_messages;
    }

    public function addTicketsMessage(TMessage $ticketsMessage): self
    {
        if (!$this->tickets_messages->contains($ticketsMessage)) {
            $this->tickets_messages[] = $ticketsMessage;
            $ticketsMessage->setOwner($this);
        }

        return $this;
    }

    public function removeTicketsMessage(TMessage $ticketsMessage): self
    {
        if ($this->tickets_messages->contains($ticketsMessage)) {
            $this->tickets_messages->removeElement($ticketsMessage);
            // set the owning side to null (unless already changed)
            if ($ticketsMessage->getOwner() === $this) {
                $ticketsMessage->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|news[]
     */
    public function getNews(): Collection
    {
        return $this->news;
    }

    public function addNews(news $news): self
    {
        if (!$this->news->contains($news)) {
            $this->news[] = $news;
            $news->setOwner($this);
        }

        return $this;
    }

    public function removeNews(news $news): self
    {
        if ($this->news->contains($news)) {
            $this->news->removeElement($news);
            // set the owning side to null (unless already changed)
            if ($news->getOwner() === $this) {
                $news->setOwner(null);
            }
        }

        return $this;
    }

    public function setNews(?news $news): self
    {
        $this->news = $news;

        return $this;
    }

    /**
     * @return Collection|NComments[]
     */
    public function getNewsComments(): Collection
    {
        return $this->newsComments;
    }

    public function addNewsComment(NComments $newsComment): self
    {
        if (!$this->newsComments->contains($newsComment)) {
            $this->newsComments[] = $newsComment;
            $newsComment->setOwner($this);
        }

        return $this;
    }

    public function removeNewsComment(NComments $newsComment): self
    {
        if ($this->newsComments->contains($newsComment)) {
            $this->newsComments->removeElement($newsComment);
            // set the owning side to null (unless already changed)
            if ($newsComment->getOwner() === $this) {
                $newsComment->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Notification[]
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications[] = $notification;
            $notification->setOwner($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): self
    {
        if ($this->notifications->removeElement($notification)) {
            // set the owning side to null (unless already changed)
            if ($notification->getOwner() === $this) {
                $notification->setOwner(null);
            }
        }

        return $this;
    }

}

src/Entity/Main/news.php
<?php

namespace App\Entity\Main;

use App\Repository\Main\newsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=newsRepository::class)
 */
class news
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="news")
     */
    private $owner;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\OneToMany(targetEntity=NComments::class, mappedBy="news")
     */
    private $newsComments;

    public function __construct()
    {
        $this->newsComments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getOwner(): ?Users
    {
        return $this->owner;
    }

    public function setOwner(?Users $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return Collection|NComments[]
     */
    public function getNewsComments(): Collection
    {
        return $this->newsComments;
    }

    public function addNewsComment(NComments $newsComment): self
    {
        if (!$this->newsComments->contains($newsComment)) {
            $this->newsComments[] = $newsComment;
            $newsComment->setNews($this);
        }

        return $this;
    }

    public function removeNewsComment(NComments $newsComment): self
    {
        if ($this->newsComments->contains($newsComment)) {
            $this->newsComments->removeElement($newsComment);
            // set the owning side to null (unless already changed)
            if ($newsComment->getNews() === $this) {
                $newsComment->setNews(null);
            }
        }

        return $this;
    }
}

src/Entity/Server/players.php
<?php

namespace App\Entity\Server;

use App\AppBundle\RankMethods;
use App\Repository\Server\playersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=playersRepository::class)
 */
class players
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $uuid;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $amis;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $server;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $groupe;

    /**
     * @ORM\Column(type="integer")
     */
    private $pj;

    /**
     * @ORM\Column(type="integer")
     */
    private $pb;

    /**
     * @ORM\Column(type="blob")
     */
    private $cosmetic;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ip;

    public function __construct()
    {
        $this->topics = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    public function getAmis()
    {
        return $this->amis;
    }

    public function setAmis(String $amis): ?string
    {
        $this->amis = $amis;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getServer(): ?string
    {
        return $this->server;
    }

    public function setServer(string $server): self
    {
        $this->server = $server;

        return $this;
    }

    public function getGroupe(): ?string
    {
        return $this->groupe;
    }

    public function setGroupe(string $groupe): self
    {
        $this->groupe = $groupe;

        return $this;
    }

    public function getPj(): ?int
    {
        return $this->pj;
    }

    public function setPj(int $pj): self
    {
        $this->pj = $pj;

        return $this;
    }

    public function getPb(): ?int
    {
        return $this->pb;
    }

    public function setPb(int $pb): self
    {
        $this->pb = $pb;

        return $this;
    }

    public function getCosmetic()
    {
        return $this->cosmetic;
    }

    public function setCosmetic($cosmetic): self
    {
        $this->cosmetic = $cosmetic;

        return $this;
    }

    public function getIp(): ?string
    {
        return $this->Ip;
    }

    public function setIp(string $Ip): self
    {
        $this->Ip = $Ip;

        return $this;
    }

    public function getRankColor(){

        return (new RankMethods())->getRank($this->groupe)['color'];
    }

    function isAdmin(){
        $power = (new RankMethods())->getRank($this->groupe)['power'];
        if($power>=5)return true;
        return false;

    }
}

templates/forum/forum.html.twig
{% extends 'forum/forum_base.html.twig' %}

{% block stylesheets_form %}
    <link rel="stylesheet" href="{{ asset('css/forum/forum.css') }}">
{% endblock %}

{% block body_form %}

    <div class="whiteBackGround">

        {% for category in categories %}

            <div class="background_cat ribbon left-bottom right-top">
                <h1 class="cat">
                    <a href="{{ path('forum') }}/{{ category.id }}">
                        <i class="fas fa-folder-open"></i> {{ category.name }}
                    </a>
                </h1>
            </div>

            <ol>

                {% for sub_category in category.subcategories %}

                    <div class="table_line">
                        <li class="flex table_line_block">

                            <div class="souscategorie topics">
                                <a href="{{ path('forum') }}/{{ category.id }}.{{ sub_category.id }}">
                                    <h2 class="sub_cat">
                                        <i class="fas fa-comment"></i> {{ sub_category.name }}
                                    </h2>
                                </a>
                            </div>

                            <div class="table_info">
                                <h2>
                                    <i class="fas fa-file-signature"></i> {{ sub_category.topics | length }}
                                </h2>
                            </div>

                            {% set last_topic_index = sub_category.topics | length - 1%}

                            {% if last_topic_index >= 0 %}

                                <div class="last_msg">

                                    <img src="https://minotar.net/helm/{{ sub_category.topics[last_topic_index].owner.username }}/64.png" alt="" class="head"/>

                                    {% set account_server = findOneBy(repo_user_server, { 'pseudo': sub_category.topics[last_topic_index].owner.username }) %}

                                    <p>
                                        <i class="fas fa-reply-all"></i>

                                        {{ sub_category.topics[last_topic_index].title }}

                                        <br>de <span style="color: {{ account_server.getRankColor() }}; ">{{ sub_category.topics[last_topic_index].owner.username }}</span>

                                    </p>

                                </div>

                            {% else %}

                                <h2 class="last_msg center"><i class="fas fa-reply-all"></i> Aucun</h2>

                            {% endif %}

                        </li>
                    </div>

                {% endfor %}

            </ol>

        {% endfor %}

    </div>

{% endblock %}

templates/forum/forum_subcategories.html.twig
{% extends 'forum/forum_base.html.twig' %}

{% block stylesheets_form %}
    <link rel="stylesheet" href="{{ asset('css/forum/forum.css') }}">
{% endblock %}

{% block body_form %}

    <div class="whiteBackGround">

        <div class="whiteBackGround">

                <div class="background_cat ribbon left-bottom right-top">
                    <h1 class="cat ">
                        <a href="{{ path('forum') }}/{{ category.id }}">
                            <i class="fas fa-folder-open"></i> {{ category.name }}
                        </a>
                    </h1>
                </div>

                <ol>

                    {% for sub_category in sub_categories %}

                        <div class="table_line">
                            <li class="flex table_line_block">

                                <div class="souscategorie">
                                    <a href="{{ path('forum') }}/{{ category.id }}.{{ sub_category.id }}">
                                        <h2 class="sub_cat">
                                            <i class="fas fa-comment"></i> {{ sub_category.name }}
                                        </h2>
                                    </a>
                                </div>

                                <div class="table_info">
                                    <h2>
                                        <i class="fas fa-file-signature"></i> {{ sub_category.topics | length }}
                                    </h2>
                                </div>

                                {% set last_topic_index = sub_category.topics | length - 1%}

                                {% if last_topic_index >= 0 %}

                                    <div class="last_msg">

                                        <img src="https://minotar.net/helm/{{ sub_category.topics[last_topic_index].owner.username }}/64.png" alt="" class="head"/>

                                        <p>
                                            <i class="fas fa-reply-all"></i>

                                            {{ sub_category.topics[last_topic_index].title }}

                                            <br>de <span style="color: red; ">{{ sub_category.topics[last_topic_index].owner.username }}</span>

                                        </p>

                                    </div>

                                {% else %}

                                    <h2 class="last_msg center"><i class="fas fa-reply-all"></i> Aucun</h2>

                                {% endif %}

                            </li>
                        </div>

                    {% endfor %}

                </ol>

        </div>

        {% if app.user %}

            <a href="{{ path('create_topic') }}/{{ category.id }}">
                <div class="button">
                    <i class="fas fa-plus"></i> Créer un nouveau Topic
                </div>
            </a>

        {% endif %}

    </div>

{% endblock %}

templates/forum/forum_topics.html.twig
{% extends 'forum/forum_base.html.twig' %}

{% block stylesheets_form %}
    <link rel="stylesheet" href="{{ asset('css/forum/forum.css') }}">
{% endblock %}

{% block body_form %}

    <div class="whiteBackGround">

        <div class="background_cat ribbon left-bottom right-top">
            <h1 class="cat">
                <i class="fas fa-comment"></i> {{ sub_category.name }}
            </h1>
        </div>

        <ol>

            {% for topic in topics %}
                <div class="table_line">
                    <li class="flex table_line_block">

                    <div class="souscategorie">
                        <a href="{{ path('forum') }}/{{ category.id }}.{{ sub_category.id }}/{{ topic.get_url_custom_encode_title() }}.{{ topic.id }}">
                            <h2 class="topic">
                                <i class="fas fa-file-signature"></i> {{ topic.title }}
                            </h2>
                        </a>
                    </div>

                    <div class="table_info">
                        <h2>
                            <i class="fas fa-reply"></i> {{ topic.messages | length }}
                        </h2>
                    </div>

                    {% set last_message_index = topic.messages | length - 1%}

                    {% if last_message_index >= 0 %}

                        <div class="last_msg">

                            <img src="https://minotar.net/helm/{{ topic.owner.username }}/64.png" alt="" class="head"/>

                            <p>
                                <i class="fas fa-reply-all"></i>

                                    {{ topic.messages[last_message_index].createAt|date("d/m/Y à H:i") }}

                                <br>de <span style="color: red; ">{{ topic.owner.username }}</span>

                            </p>
                        </div>

                    {% else %}

                        <h2 class="last_msg center"><i class="fas fa-reply-all"></i> Aucun</h2>

                    {% endif %}

                    <div class="last_msg"> <img src="https://minotar.net/helm/{{ topic.owner.pseudo }}/64.png" alt="" class="head"/>
                        <p>
                            <span style="color: #F1D318; "><i class="fas fa-crown"></i></span> {{ topic.createAt|date("d/m/Y à H:i") }}<br /> de <span style="color: red; ">{{ topic.owner.pseudo }}</span></p></div>

                    </li>
                </div>
            {% endfor %}

        </ol>

    </div>

    {% if app.user %}

        <a href="{{ path('create_topic') }}/{{ category.id }}">
            <div class="button">
                <i class="fas fa-plus"></i> Créer un nouveau Topic
            </div>
        </a>

    {% endif %}

{% endblock %}

templates/forum/topic_create.html.twig
{% extends 'forum/forum_base.html.twig' %}

{% block stylesheets_form %}
    <link rel="stylesheet" href="{{ asset('css/forum/topic.css') }}">
{% endblock %}

{% block javascript_head %}
{% endblock %}

{% block body_form %}

    {{ form_start(form) }}
        <div class="whiteBackGround">
            <div class="background_cat ribbon left-bottom right-top">
                <h1 class="cat">
                    <i class="far fa-file"></i> Nouveau Topic
                </h1>
            </div>

            <section class="new_topic">

                <div class="title-box">
                    {{ form_row(form.title, {'label': 'Titre'}) }}
                </div>

                <div class="select_line">
                    <div class="select-box">
                        <select>
                            <option value="{{ category.id }}">{{ category.name }}</option>
                        </select>
                        <label>Catégorie</label>
                    </div>

                    <div class="select-box">
                        {{ form_row(form.subcategory, {'label': 'Sous-Catégorie'}) }}
                    </div>
                </div>

                <div class="content-box">
                    {{ form_row(form.content, {'label': 'Contenu'}) }}
                </div>

                <button type="submit" name="ticket_submit" class="btn">
                    Poster
                </button>

            </section>

        </div>
    {{ form_end(form) }}

{% endblock %}

templates/forum/topic_view.html.twig
{% extends 'forum/forum_base.html.twig' %}

{% block stylesheets_form %}
    <link rel="stylesheet" href="{{ asset('css/forum/topic_show.css') }}">
{% endblock %}

{% block body_form %}

    <div class="whiteBackGround">

        <div class="background_cat ribbon left-bottom right-top">
            <h1 class="cat"><i class="fas fa-file-signature"></i> Sujet du Topic:
                <span class="subject"><span style="color: orange; ">{{ topic.title }}</span></span>
            </h1>
        </div>

        {% if app.user and topic.owner.username == app.user.username %}

            <form method="POST">
                <input class="button_delete" type="submit" name="delete_topic_submit" value="⚠ Supprimer le topic">
            </form>

        {% endif %}

        <ol>

            <!-- OWNER POST -->

            <li class="flex">

                <div class="topic_poster">
                    <div class="avatar">
                        <div>
                            <h2>
                                <span style="color: #F1D318; "><i class="fas fa-crown"></i> <span class="hide_responsive">Propriétaire</span></span>
                            </h2>
                            <img src="https://minotar.net/helm/{{ topic.owner.pseudo }}/100.png" alt="" class="head"/>
                            <h2 class="poster_name ribbon left-top right-top">{{ topic.owner.pseudo }}</h2>
                        </div>

                        <div class="auteur_info">

                            <p>INSCRIPTION: <br>{{ topic.owner.date | date("d/m/Y à H:i") }}</p>
                            <p>GRADE: <br><span style="color: {{ user_server.rankColor }}; "> {{ user_server.groupe }}</span></p>
                        </div>
                    </div>
                </div>

                <div class="topic_msg">

                    {{ content | raw }}

                </div>

            </li>

            <!-- RESPONSES -->

            <h2 class="responses_title"><i class="fas fa-reply"></i> Réponses<hr class="responses_separator"></h2>

            {% for response in responses %}

                <li class="flex">

                    <div class="topic_poster">
                        <div class="avatar">
                            <div>

                                {% if response.owner.pseudo == topic.owner.pseudo %}

                                    <h2><span style="color: #F1D318; "><i class="fas fa-crown"></i> <span class="hide_responsive">Propriétaire</span></span></h2>

                                {% endif %}

                                <img src="https://minotar.net/helm/{{ response.owner.pseudo }}/100.png" alt="" class="head"/>

                                <h2 class="poster_name ribbon left-top right-top">{{ response.owner.pseudo }}</h2>
                            </div>

                            <div class="auteur_info">

                                {% set account_server = findOneBy(repo_user_server, { 'pseudo': response.owner.pseudo }) %}

                                <p>INSCRIPTION: <br>{{ response.owner.date | date("d/m/Y à H:i") }}</p>

                                {% if account_server is not null %}
                                    <p>GRADE: <br><span style="color: {{ account_server.rankcolor }}; "> {{ account_server.groupe }}</span></p>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <div class="topic_msg">
                        <p>
                            {{ response.content }}
                        </p>
                    </div>
                </li>

            {% endfor %}

            <div class="pagination">

                {% if page_nb > 1 %}

                    <a href="{{ path('forum') }}/{{ category.id }}.{{ sub_category.id }}/{{ topic.get_url_custom_encode_title() }}.{{ topic.id }}/{{ page_nb - 1 }}"><div class="pages_nb no_cliqued">Précedente</div></a>

                {% endif %}

                {% for i in range(1, page_count) %}

                    {% if i == page_nb %}

                        <div class="pages_nb cliqued">
                            {{ i }}
                        </div>

                    {% else %}

                        <a href="{{ path('forum') }}/{{ category.id }}.{{ sub_category.id }}/{{ topic.get_url_custom_encode_title() }}.{{ topic.id }}/{{ i }}">
                            <div class="pages_nb no_cliqued">
                                {{ i }}
                            </div>
                        </a>

                    {% endif %}

                {% endfor %}

                {% if page_nb < page_count %}

                    <a href="{{ path('forum') }}/{{ category.id }}.{{ sub_category.id }}/{{ topic.get_url_custom_encode_title() }}.{{ topic.id }}/{{ page_nb + 1 }}">
                        <div class="pages_nb no_cliqued">
                            Suivante
                        </div>
                    </a>

                {% endif %}

            </div>

        </ol>

        <div class="response">
            {% if app.user %}

                <form method="POST">
                    <textarea placeholder="Votre Réponse" name="tresponse">{% if response_content is not null %}{{ response_content }}{% endif %}</textarea>
                    <input class="button" type="submit" name="tresponse_submit" value="Poster la réponse">
                </form>

                {% if msg is not null %}

                    {{ msg }}

                {% endif %}

            {% else %}

                <p class="error"><span style="color: red; "><i class="fas fa-exclamation-triangle"></i> Merci de vous connecter pour poster une réponse</span></p>

            {% endif %}
        </div>

    </div>

{% endblock %}